### PR TITLE
Fixed issue where the first type was always recognized as the global …

### PR DESCRIPTION
**Pull request by LMSDev**
…type. Not entirely about the detection method, but should do it. For assemblies where <Module> and other stuff is stripped, I had to add this to get Confuser to resolve properly. Nice project btw. - LMS

### CODE REVIEW

**Comment by LMSDev** [comment]
Apparently GitHub didn't like the word < Module > after "where".

**Comment by 0xd4d** [comment]
The global type, aka `<Module>` type is always the first type and can be named anything.

**Comment by LMSDev** [comment]
Ah okay. Without this "fix" dnlib refuses to resolve types (rather the first/global type) for me though, because one of my references is an assembly where the < Module >  information has been stripped. Would you consider that as bad luck or is there a way we can integrate this?

**Comment by 0xd4d** [comment]
Could you email me a file? de4dot@gmail.com

**Pull request closed without merging**
