### PR TITLE
Improve IsValueType for GenericSig

### PR DESCRIPTION
**Pull request by CreateAndInject**

### CODE REVIEW

**Comment by wtfsck** [comment]
Can you explain why this is an improvement?

**Comment by CreateAndInject** [comment]
Since we know if it's ValueType exactly in these cases.

**Comment by CreateAndInject** [comment]
Reflection check type constraint also:
image

**Comment by wtfsck** [comment]
This resolves a type which no other function in that file does. It's better if you create an extension method to your code and add this code to it.

**Pull request closed without merging**
