### PR TITLE
'=' is not an special char for TypeName

### PR DESCRIPTION
**Pull request by yyjdelete**
Align with the logic in `FullNameFactory.AddIdentifier(string)` and `ReflectionExtensions.IsReservedTypeNameChar(char)` in dnlib and `ResourceRenamer.IsReservedTypeNameChar(char)` in de4dot

### CODE REVIEW

**Comment by 0xd4d** [comment]
It can't be removed because it's used to stop when there's an `=` in `key=value`, eg. `PublicKeyToken=xxxxx`.

**Comment by yyjdelete** [comment]
Ok, I didn't see the code here.
https://github.com/0xd4d/dnlib/blob/2cbe552792769895991b5e1e3bd130526a12e2ed/src/DotNet/TypeNameParser.cs#L743-L748

But seems the usage below should ignore '='(hit this with renamer in ConfuserEx), maybe needed add another check option or reuse `ignoreWhiteSpace`.
https://github.com/0xd4d/dnlib/blob/2cbe552792769895991b5e1e3bd130526a12e2ed/src/DotNet/TypeNameParser.cs#L358-L363

**Comment by 0xd4d** [comment]
What does the type ref name look like and is it a valid name?

If so we could add a new bool arg to `ReadId(bool)`

**Comment by yyjdelete** [comment]
As an example, when you compile the below code and rename `Test` to `Te=st` with dnSpy, you can still execute it without exception and get `ConsoleApp1.Te=st`, but unable to see `[Custom(Type = typeof(Test))]` (only `[Custom]` is shown) in dnSpy.
```cs
using System;
using System.Reflection;

namespace ConsoleApp1
{
	public class Test { }
	[Custom(Type = typeof(Test))]
	public class CustomAttribute : Attribute {
		public Type Type { get; set; }
	}
	class Program {
		static void Main(string[] args) {
			Console.WriteLine(typeof(CustomAttribute).GetCustomAttribute<CustomAttribute>().Type);
		}
	}
}
```

**Comment by 0xd4d** [comment]
Thanks for the repro. Do you want to update your PR? I think all we need is an extra bool parameter that decides if `=` should be treated as an id char or not.

**Pull request closed without merging**
