### PR TITLE
Fixes calling ResolveTypeSpec without gpContext causing listTypeSpecMD polluted

### PR DESCRIPTION
**Pull request by wwh1004**

### CODE REVIEW

**Comment by wtfsck** [comment]
That check was added due to: https://github.com/0xd4d/dnlib/issues/331

Have you tested your code with the code from that issue?

**Comment by wtfsck** [comment]
Seems like the only problem is that it doesn't find the generic parameter in the type so it can't print the GP name, only its GP index. It shouldn't be a problem.

**Comment by wwh1004** [comment]
The TypeSpec I printed is in instruction read by MethodBodyReader, which is read with gpContext. 
https://github.com/0xd4d/dnlib/blob/master/src/Utils/SimpleLazyList.cs#L84
When I resolve TypeSpec without gpContext, 'elem.ContainsGenericParameter' will return false and result will be cached in 'elements[index]'. After that no matter what gpContext I pass to resolve TypeSpec, it will return the cached item but not construct a new one by reading with gpContext.

**Comment by wwh1004** [comment]
> That check was added due to: #331
> 
> Have you tested your code with the code from that issue?

I patched dnSpy's dnlib with this fix and load 'HelloWorld.MaliciousTypeSpecLoop.exe', dnSpy doesn't hang.

**Review by wtfsck — APPROVED** [review]

**Comment by wtfsck** [comment]
Thanks for testing it! Merged.

**Pull request merged**
