### PR TITLE
Compare reference only for MemberDefs if they are from the same module

### LINKED ISSUE #450: Why does dnlib compare two MemberDef by name?
Why `a == b` is not enough?
image

```
class Program
{
    int a;
    int b;
}
```
Rename b to a by dnSpy, then SigCompare will think it's the same field, but it's not in fact.

### PR DESCRIPTION
**Pull request by CreateAndInject**
Fix #450

### CODE REVIEW

**Comment by ElektroKill** [comment]
I suggest we add a additional signature compared flag to revert to the old behavior to allow easy adaptation of code from v3 to v4.

**Comment by CreateAndInject** [comment]
>It's useful when you open the same assembly but two different versions and need to compare defs.

We should add an option if we don't check if they are from the same module to fix above issue.

But if we already checked the module, no reason to add such option, since it just fix the bug but doesn't take any side effect, unless we can imagine an example which old code work fine but new code make wrong.

**Comment by wtfsck** [comment]
Yes an option to revert to the old behavior is needed.

> since it just fix the bug

It's not a bug as explained in the linked issue.

**Review by wtfsck — APPROVED** [review]

**Comment by wtfsck** [comment]
Thanks!

**Pull request merged**
