### PR TITLE
Clean moduleSearchPaths

### PR DESCRIPTION
**Pull request by CreateAndInject**
By the way, is there any issue in .editorconfig file? The code is always changed when formating (Ctrl + E, D)

### CODE REVIEW

**Comment by wtfsck** [comment]
> By the way, is there any issue in .editorconfig file? The code is always changed when formating (Ctrl + E, D)

It's probably the `#if THREAD_SAFE` stuff that the formatter doesn't like.

**Comment by wtfsck** [comment]
Thanks, merged!

**Comment by CreateAndInject** [comment]
Mark: Fix OutOfMemoryException when handle hundreds of files one by one in 32bit process.

**Comment by CreateAndInject** [comment]
@wtfsck Can you bump version? I need this commit to fix OutOfMemoryException.

**Comment by wtfsck** [comment]
@CreateAndInject Done

**Pull request merged**
